### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mewmew** [mewkiz/flac#33]
# Version 1.x

*Before move to `github.com/ljud`*. (see #19)

- [x] remove `flac.Encode` (done as of #32)
- [ ] rename `internal/bits` to `internal/bitio`.
- [ ] copy `icza/bitio` to `internal/bitio` to reduce external dependencies.
- [ ] rename `enc_test.go` to `encode_test.go` and update to make use of `NewEncoder`.
- [ ] add encode/decode round-trip test case

# Version 2.x

*After move to `github.com/ljud`*. (see #19)

- [ ] make `Header` and `SubHeader` of `frame.Frame` and `frame.Subframe` pointers instead of values?
- [ ] rename `frame.SubHeader.Wasted` to `WastedBits`?
- [ ] check if we could add a `Decoder` analogous to `Encoder`, and remove unexported readers from `flac.Stream`, `frame.Frame` and `frame.Subframe`.

**Comment by wsc1** [comment]
Just curious, why seek with time.Duration?   the frame number is more precise, and necessary in the context of DAWs splicing, etc, which might use a flac backend.

**Comment by mewmew** [comment]
> Just curious, why seek with time.Duration? the frame number is more precise, and necessary in the context of DAWs splicing, etc, which might use a flac backend.

I've updated the seek bullet item now to include sample numbers as well. The `time.Duration` version of seek is mainly intended for end-users wishing to implement music players and the like, where sample number perfection is less important than the intuition of API to say, seek to the time point 01:00 in the song.

As of late, @mehrvarz has been playing around with getting a FLAC music player to work on raspberry pi. Thus helping to uncover where the API falls short for such use cases.
